#!/usr/bin/env ruby

require 'parslet'
require_relative 'parser'
require_relative 'interpreter'

begin
  parser = Parser.new
  ast = parser.parse(File.read(ARGV[0]))
  interpreter = Interpreter.new(ast)
rescue Parslet::ParseFailed => failure
  puts "SYNTAX ERROR"
  puts failure.cause.ascii_tree
rescue RuntimeError => failure
  puts "RUNTIME ERROR"
  puts failure.message
end
